# Generated by Django 3.2 on 2025-11-05 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LoadUnload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateField()),
                ('transaction_type', models.CharField(choices=[('Load', 'Load'), ('Unload', 'Unload')], max_length=10)),
                ('truck_no', models.CharField(max_length=50)),
                ('challan_no', models.CharField(max_length=50)),
                ('box_type', models.CharField(choices=[('Bale', 'Bale'), ('Box', 'Box'), ('Bag', 'Bag'), ('Drum', 'Drum'), ('Cartoon', 'Cartoon')], max_length=20)),
                ('box_qty', models.PositiveIntegerField()),
                ('qty_type', models.CharField(choices=[('kg', 'Kilogram'), ('meter', 'Meter'), ('pcs', 'Pieces')], max_length=10)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rate_per_qty', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_transactions', to='mainapp.party')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.item')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplied_transactions', to='mainapp.party')),
            ],
        ),
    ]
