# Generated by Django 3.2 on 2025-11-05 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_loadunload_customer_alter_loadunload_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loadunload',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customer_transactions', to='mainapp.party'),
        ),
        migrations.AlterField(
            model_name='loadunload',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mainapp.item'),
        ),
        migrations.AlterField(
            model_name='loadunload',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supplied_transactions', to='mainapp.party'),
        ),
    ]
